import Head from "next/head";
import "./globals.css";
import "./reset.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Chess TRVL</title>
      </head>
      <body id="#">{children}</body>
    </html>
  );
}
